import { chromium, expect } from '@playwright/test';
const base=process.env.TEST_URL || 'http://127.0.0.1:3210';
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1080}});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
let id;
try {
  await page.route('**/api/articles',async route=>{
    if(route.request().method()!=='POST')return route.continue();
    const body=route.request().postDataJSON();
    await route.continue({postData:JSON.stringify({...body,process:false}),headers:{...route.request().headers(),'content-type':'application/json'}});
  });
  await page.goto(base);
  await expect(page.getByRole('heading',{name:'Your library.'})).toBeVisible();
  await page.getByRole('button',{name:'Text',exact:true}).click();
  await page.getByLabel('Article text',{exact:true}).fill('This is an automated browser test for redread. The article should be saved as a draft. The original text and listening version remain separate. The article is deleted after the test.');
  await page.getByRole('button',{name:'Options',exact:true}).click();
  await page.getByLabel('Title (optional)',{exact:true}).fill('Browser test: An article for the road');
  await page.getByRole('button',{name:'Close options'}).click();
  await page.getByRole('button',{name:'Add article',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Article saved as a draft.');
  const items=await (await page.request.get(base+'/api/articles')).json();id=items.find(a=>a.title==='Browser test: An article for the road').id;
  await page.getByRole('button',{name:'Open article: Browser test: An article for the road'}).click();
  await expect(page.getByRole('dialog').getByRole('heading',{name:'Browser test: An article for the road'})).toBeVisible();
  await page.getByRole('button',{name:'Listening version',exact:true}).click();
  await expect(page.getByRole('heading',{name:'No listening version yet.'})).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('heading',{name:'Browser test: An article for the road'})).toBeVisible();
  await page.goto(`${base}/?article=${id}`);
  await expect(page.getByRole('dialog').getByRole('heading',{name:'Browser test: An article for the road'})).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByLabel('Search library').fill('nomatchingarticles');
  await expect(page.getByRole('heading',{name:'No matching articles.'})).toBeVisible();
  await page.getByRole('button',{name:'Reset filters'}).click();
  await page.screenshot({path:'/tmp/redread-library.png',fullPage:true});
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await expect(page.getByLabel('LLM base URL')).toBeVisible();
  await expect(page.getByLabel(/TTS base URL|Fish Audio TTS URL/)).toBeVisible();
  await expect(page.getByRole('heading',{name:'Your podcast'})).toBeVisible();
  await expect(page.getByLabel('Feed title')).toBeVisible();
  await expect(page.getByLabel('Accessible app URL')).toBeVisible();
  await page.screenshot({path:'/tmp/redread-settings.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'/tmp/redread-mobile-settings.png',fullPage:true});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('Mobile settings overflow');
  await page.getByRole('button',{name:/Library/}).click();
  await page.screenshot({path:'/tmp/redread-mobile.png',fullPage:true});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('Mobile library overflows');
  if(errors.length)throw new Error(errors.join('\n'));
  console.log('Browser checks passed: import, persistence, reader, search, settings, and mobile layout; no browser errors.');
} finally {
  if(id)await page.request.delete(base+`/api/articles/${id}`,{headers:{'Content-Type':'application/json'}});
  await browser.close();
}
