import { chromium, expect } from '@playwright/test';
const base=process.env.TEST_URL || 'http://127.0.0.1:3210';
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1080}});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
let id;
try {
  await page.goto(base);
  await expect(page.getByRole('heading',{name:'Deine Bibliothek.'})).toBeVisible();
  await page.getByRole('button',{name:'Artikel hinzufügen',exact:true}).click();
  await page.getByRole('button',{name:'Text einfügen',exact:true}).click();
  await page.getByLabel('Artikeltext',{exact:true}).fill('Dies ist ein automatisierter Browsertest für redread. Der Artikel soll als Entwurf gespeichert werden. Originaltext und Hörfassung bleiben getrennt erhalten. Nach dem Test wird dieser Artikel wieder gelöscht.');
  await page.getByLabel('Titel',{exact:false}).fill('Browsertest: Ein Artikel für unterwegs');
  const autoProcess=page.getByRole('checkbox');
  if(await autoProcess.count())await autoProcess.uncheck();
  await page.getByRole('dialog').getByRole('button',{name:'Artikel hinzufügen',exact:true}).click();
  await expect(page.getByRole('dialog').getByRole('heading',{name:'Browsertest: Ein Artikel für unterwegs'})).toBeVisible();
  const items=await (await page.request.get(base+'/api/articles')).json();id=items.find(a=>a.title==='Browsertest: Ein Artikel für unterwegs').id;
  await page.getByRole('button',{name:'Hörfassung',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Noch keine Hörfassung.'})).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('heading',{name:'Browsertest: Ein Artikel für unterwegs'})).toBeVisible();
  await page.goto(`${base}/?article=${id}`);
  await expect(page.getByRole('dialog').getByRole('heading',{name:'Browsertest: Ein Artikel für unterwegs'})).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByLabel('Bibliothek durchsuchen').fill('keinepassendenartikel');
  await expect(page.getByRole('heading',{name:'Keine passenden Artikel.'})).toBeVisible();
  await page.getByRole('button',{name:'Filter zurücksetzen'}).click();
  await page.screenshot({path:'/tmp/redread-library.png',fullPage:true});
  await page.getByRole('button',{name:'Einstellungen',exact:true}).click();
  await expect(page.getByLabel('LLM-Basis-URL')).toBeVisible();
  await expect(page.getByLabel(/TTS-Basis-URL|Fish Audio TTS-URL/)).toBeVisible();
  await page.getByRole('button',{name:'Einstellungen speichern'}).click();
  await expect(page.getByRole('status')).toContainText('Einstellungen gespeichert.');
  await page.screenshot({path:'/tmp/redread-settings.png',fullPage:true});
  await page.getByRole('button',{name:'Mein Podcast',exact:true}).click();
  await expect(page.getByLabel('Podcastfeed-URL')).toHaveValue(`${base}/feed.xml`);
  await page.getByRole('button',{name:'Feed-Link kopieren'}).click();
  await expect(page.getByRole('status')).toContainText('Link kopiert.');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'/tmp/redread-mobile-feed.png',fullPage:true});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('Mobile feed overflows');
  await page.getByRole('button',{name:/Bibliothek/}).click();
  await page.screenshot({path:'/tmp/redread-mobile.png',fullPage:true});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('Mobile library overflows');
  if(errors.length)throw new Error(errors.join('\n'));
  console.log('Browser checks passed: import, persistence, reader, search, settings, feed, mobile layout; no browser errors.');
} finally {
  if(id)await page.request.delete(base+`/api/articles/${id}`,{headers:{'Content-Type':'application/json'}});
  await browser.close();
}
